### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by ClazyCoder** [PastelDew/PDStereo#1]
환경 세팅이 안됩니다. (Error had occurred while setting running environment)
![Error](https://user-images.githubusercontent.com/17492903/60700260-2df93a00-9f32-11e9-9a49-83962492ef07.PNG)

**Comment by PastelDew** [comment]
Shapely모듈을 윈도우 환경에서 설치 할 때 발생하는 문제입니다.
다음 링크들을 참고하여주시기 바랍니다.
> https://stackoverflow.com/questions/44398265/install-shapely-oserror-winerror-126-the-specified-module-could-not-be-found
> https://gis.stackexchange.com/questions/62925/why-is-shapely-not-installing-correctly/62931

해당 모듈을 설치한 뒤 진행하시면 문제 없이 설치가 진행됩니다.
